---
gui:
  nerdFontsVersion: '3'
  border: rounded
  theme:
    activeBorderColor: ['#8aadf4', bold]
    inactiveBorderColor: ['#494d64']
    optionsTextColor: ['#8aadf4']
    selectedLineBgColor: ['#363a4f']
    selectedRangeBgColor: ['#363a4f']
    cherryPickedCommitBgColor: ['#363a4f']
    cherryPickedCommitFgColor: ['#c6a0f6']
    unstagedChangesColor: ['#ed8796']
    defaultFgColor: ['#cad3f5']
    defaultBgColor: ['#24273a']
  authorColors:
    Clarissa Gunawan: '#ebcb8b'
